var d = new Date();
var year = d.getFullYear().toString();
var m = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
var month = m[d.getMonth()];
var footer = "";
var footer0 = "MaX Falstein gTLD &copy; MaX Falstein and Falstein Inc. &#8212; ";
var footer1 = " ";
var footer2 = " &#8212; Patents and Trademarks Pending";
footer = footer0.concat(month.concat(footer1.concat(year.concat(footer2))));
document.getElementById("footer").innerHTML = footer;
